{% set version = "2.19.1" %}
{% set minor_ver = '.'.join(version.split('.')[:2]) %}

package:
  name: hdfeos2
  version: {{ version }}

source:
  - url: ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/HDF-EOS{{ minor_ver }}v1.00.tar.Z
    sha256: 3fffa081466e85d2b9436d984bc44fe97bbb33ad9d8b7055a322095dc4672e31
    patches:
      # https://lists.gnu.org/archive/html/guix-devel/2016-09/msg02110.html
      - 0001-fix-automake-files-for-linux-compatibility.patch
  - url: ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/HDF-EOS{{ minor_ver }}v1.00_TestDriver.tar.Z
    sha256: 170c1b515d67897a739779de22c0f046e0ee927f9b7567445e68861a018b7c2d

build:
  number: 9
  skip: True  # [win]
  # static libs.  No run_exports.
  # run_exports:
  #   # no info.  Leaving at minor.
  #   - {{ pin_subpackage('hdfeos2', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
  host:
    - hdf4
    - zlib
    - jpeg

test:
  commands:
    - test -f ${PREFIX}/lib/libGctp.a  # [not win]
    - test -f ${PREFIX}/lib/libhdfeos.a  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://hdfeos.org/index.php
  license: Public Domain
  summary: 'Earth Observing System HDF.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
