travis:
  secure:
    BINSTAR_TOKEN: pFM4XeoLRKHijTm9yJQxvGq1gOwaawI75ZaR/y99mCjq+uePWhH4poYxxVNnKuukBOghIh2Y3Pz6II+yK8cy1xok6pVU3yPpAc1oNAw65vKY6+F0qN+mdXszVXECNcYsztuqCiBZSpw1SUv3xMTR37fL13/RxvCJv2R+G+FUWMSiKuWRefiZqhAkSsybklwXyYIPHPXYBBe7qo/2J+rVEamB/YPXPKYhxXMNegqDmD3Z00BWPqOsWZAqLa0yQCJZSB9VwYS5aVqvS42ABFbz+xKObyH2aIAzV1WBphhWONQvuKS0mKxB5ScEot47kNyU5CKQw7hDNJT3UOg+IIOa15aY6znnfcTA9OrLHCndeQfBZfTjztKUv68xV9OAISSp/uwONZMqxeBfsRcJDBsSDAAiVWAT7d0e7LkI/ivgjjlKLLBIuf4GwIF4tD8y4gRM7y66pnPIzslJJ94j23dHfCNP1VSokPT0pQfDoqRSC+yYel4hiXOQ4wNyeWTeIptr4DInCjipitt7ldC+xJdPIu2Itv1sAHskr1mIMh0QPmpwZ3VIEVHWfpqfXUy8l2cYdmjUziz4f12ddAPEGb04cdiJApxrZPwRnUbBg7v85FoKRy6dWRXmTNNFwnKpYmzVKKea+DgOdBHSnzgN1zxq26yV7xPadLH1RWhQiaswqPc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
