travis:
  secure:
    BINSTAR_TOKEN: zqAyU8e1jfxbzNZgglfUMs9CPakObgVWP2KJc4nzMFywqufk0sYAv+Qs7+lJfl2Fa7zYxIKGtlcZOG6sIfgoSP0X+PdIhzg3cPwx7FwT6K7w98f1+yaJQ8VpB8git9i2Retr+jYm8NPomsGNLulcD2K0BeNpaYp2i/CUPBlu1f8hVq/qsBAnf34YDQb9LQeONx/Ys3/9XrJ9oE7lNsg0CkZroHhSprc0hvm4DM/hB+kbHE/XJsgZuVxSS6zxUwGy2x+kvEpFOG6+BhHDdv2OitLwb+WZVjY/RS6BFx/AfkkikICUVCQTrGYBrLkjXOCg1nsn/pLXWpsULBK09s40SGCI4KzHKNp3pY50Bt2CgsW42WvR4rC8VAaIe/pQpVtjZK5g+2XoDBOdNrN9KHv/GU58bAnjWaPSy/GXRUUpQfa5Oa/Az2F7bR50P9cyErsxndnyVMDYNhyksJDOk67OTgc2VTl+Vowjjf16vnDzJIFRaVUx9Dv3ou56GDp/0Abjpd2c+0krNH8Fqv0oknqX6pcqSxdBqm7dEe7Bd8eNO+6HfB2LjcUCtW321WXc7CWRIGuo7a6h++b57eekippOUalJb35yvB1hsh9pN/IpT5PjTi98pwsq0qwcUamHZyOXbhfSjoQqu1y62eF+mazB87YvpNEsXg7I0USbeVs1A+8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
