travis:
  secure:
    BINSTAR_TOKEN: 2JrOyEsh0KAWBpB5BiSgeazqaoa2Cgmo1dot4eDlmE+x44TSy8dLx0+s+A0rKCdzKNsRDQyNQw7oz2YPuMOeWEwbfEaLa7hpxZQETcImRNFpOyCV4Q9csbAWoUzV9xlG3blyKcLYKzS39V21Zt4j5iVSZ6JnHt1qCmGsVX1lPyxxi6C1+8ao4LnYLq2JVCWmSQgYHa8SL4gXPN0XJ1cKpg2Stp9X9M/3ZZvCDjyYwCj7GZfva9sQAD6R5CFV48OpA9FiBNfnID1ZYZAaUYY5pgiH0CveOKlICU6IfTa823oMjkQ6d537Syce1kIOS0GpsK76DosYfOj0zdkeYJj2CQ0kR/xKAOiyYrU0KBy4MppFAkIEA4ziSfSVz/ij3+c/0IzSMHgsoxm3p4lbc0spbfPfNJYSrNH7/9tNgmeLatZqwdNS7uRqGDEwDoa0raVmFtD3/hYS1rjCMyo8RgBIB+93OYmFGae71Wzj5FculJ3QAWN90tQ6J35ODe7ltJ7SYimDxaEY0vElqSwsa1xGL43kttSMfsaOpuz7Zzgasw8j8MR3W9KjkFdBYyTN2J1PSC6PO8wPagdS2xnEaqN1NS1ip/GbpEw3uWlTPxkpKGfa8Be63w/s39usQjGMTzbx9NvCBMn8nJM5kKDDDN4iX9iDis8TVlCC9E5QCQ9snY0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
