travis:
  secure:
    BINSTAR_TOKEN: GIgMXYvmJsb1pKmGBbT1pICYksMEDSZ8xPpguXFRc/N/t1w8MQAF8hAwK2+6jV9AmVY3ih3b/5PHeDdzT8T4fKSMOPBlI6l5rHYFWQfqIeByh8mnS+aUqdBJnv/eXujIdYOU8Qj1583F6J1XX0VawcJydHj3j9VU3wQdZNx4d3IptPlzhyVaS+TYKjOrJ7C2qtBn9E+1h1EdCFlixEbhup3VVSYmhwbjS8WlmN79PRtodbhXc5hf4vc3bBrSJG1/hgENqCDBdBLt+q2r/5ObVzPn7QSgjZz02CwOdUoa1X0hF5Sh+xLjWM+/Fg9DPaaLfZS6Zu7nJ7TwkAfJ+j1mvGlX81nhwtJksQd06hVGBxeA3976N8MG9o4ENvqpwkdMSaThA3AsyLbC9LV0BRN891GVOp8GLg25cGVL+5hj/3MYSoeh6pTWF3bFeDRwTUXnp51xUHCC3fjg1SPS1E1Ii8bPqupS3PHQUysO74uoeAoXe9b4GqTXY7IbPQUxIfK3qk9ZBF3Y6uXh8OjwsYflbh1Hhdk+gOKReCRpkyxTVo1KUk4m6z6B4YOlfQea5P+7dJucywyPF58G+6MigupaaXXYqY4NyfA4uZXnjxESsGgBE0bBOwcQChpDNCtNVNI6s8PdZzJQbc7q22PHb2kKX94Bfr0JFjQw0tbPSErflLk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
